name        : moka-icon-theme
version     : 5.0
release     : 3
source      :
    - https://github.com/moka-project/moka-icon-theme/raw/master/moka-icon-theme-5.0.tar.gz : 5b885928606ed582305912063a6e499947f5bcf6c6749d7da242a3b571306bbd
license     : GPL-3.0
summary     : Moka Icon Theme
description : |
    Moka is an icon theme designed with a minimal, flat style, using simple geometry & colours.
    
    Each icon has been pixel-perfectly-designed and provides several sizes for the best experience throughout your desktop.
rundeps    :
    - faba-icon-theme
install    : |
    mkdir -p $installdir/usr/share/icons/
    cp -R Moka $installdir/usr/share/icons/.
    chmod a+r -R $installdir/usr/share/icons
