name       : moka-icon-theme
version    : 5.3.5
release    : 8
source     :
    - https://github.com/snwh/moka-icon-theme/archive/v5.3.5.tar.gz : 91d1d702501fca85b7c8dedbc690884d697e482b732cd3801febd5f7c0525918
license    :
    - GPL-3.0
    - CC-BY-SA-4.0
component  : desktop.theme
summary    : Moka Icon Theme
description: |
    Moka is an icon theme designed with a minimal, flat style, using simple geometry & colours.

    Each icon has been pixel-perfectly-designed and provides several sizes for the best experience throughout your desktop.
builddeps  :
    - git
rundeps    :
    - faba-icon-theme
setup      : |
    git apply $pkgfiles/*.patch
install    : |
    mkdir -p $installdir/usr/share/icons/
    cp -R Moka $installdir/usr/share/icons/.
    chmod a+r -R $installdir/usr/share/icons
