name       : moka-icon-theme
version    : 5.4.0.4
release    : 12
source     :
    - https://github.com/UbuntuBudgie/moka-icon-theme/archive/refs/tags/v5.4.0.4.tar.gz : 211a3cca958c8ee030842df2ce792fd217b3911b728a5a45d5f4ddca3d5c1b32
license    :
    - CC-BY-SA-4.0
    - GPL-3.0-or-later
component  : desktop.theme
summary    : Moka Icon Theme
description: |
    Moka is an icon theme designed with a minimal, flat style, using simple geometry & colours. Each icon has been pixel-perfectly-designed and provides several sizes for the best experience throughout your desktop.
rundeps    :
    - faba-icon-theme
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
