name        : moka-icon-theme
version     : 5.1
release     : 4
source     :
    - https://solus-project.com/sources/moka-icon-theme-5.1.tar.xz : 661d15a5b29b95ae61cd58951fa6868aa247b1baaa7bde47972db5803f84d2b4
license     : GPL-3.0
summary     : Moka Icon Theme
description : |
    Moka is an icon theme designed with a minimal, flat style, using simple geometry & colours.
    
    Each icon has been pixel-perfectly-designed and provides several sizes for the best experience throughout your desktop.
rundeps    :
    - faba-icon-theme
install    : |
    mkdir -p $installdir/usr/share/icons/
    cp -R Moka $installdir/usr/share/icons/.
    chmod a+r -R $installdir/usr/share/icons
