name       : moka-icon-theme
version    : 5.5.0
release    : 13
source     :
    - https://github.com/UbuntuBudgie/moka-icon-theme/archive/refs/tags/v5.5.0.tar.gz : 61bd00cbbd24445ef444a726a5cc847aa157124764233a4c321eab12b2fbdd95
license    :
    - CC-BY-SA-4.0
    - GPL-3.0-or-later
component  : desktop.theme
summary    : Moka Icon Theme
description: |
    Moka is an icon theme designed with a minimal, flat style, using simple geometry & colours. Each icon has been pixel-perfectly-designed and provides several sizes for the best experience throughout your desktop.
rundeps    :
    - faba-icon-theme
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
