name       : moka-icon-theme
version    : 5.3.5
release    : 9
source     :
    - git|https://github.com/snwh/moka-icon-theme.git : 87373de8d7e2c8ad1975174a46bfdb2d3cc7a40f
license    :
    - GPL-3.0
    - CC-BY-SA-4.0
component  : desktop.theme
summary    : Moka Icon Theme
description: |
    Moka is an icon theme designed with a minimal, flat style, using simple geometry & colours.

    Each icon has been pixel-perfectly-designed and provides several sizes for the best experience throughout your desktop.
rundeps    :
    - faba-icon-theme
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
