name       : moka-icon-theme
version    : 5.4.0
release    : 11
source     :
    - https://github.com/snwh/moka-icon-theme/archive/v5.4.0.tar.gz : b32e82aea4358e087620e852aa20042e791aa957a93de568da1d2223a46c7cd9
license    :
    - GPL-3.0
    - CC-BY-SA-4.0
component  : desktop.theme
summary    : Moka Icon Theme
description: |
    Moka is an icon theme designed with a minimal, flat style, using simple geometry & colours.

    Each icon has been pixel-perfectly-designed and provides several sizes for the best experience throughout your desktop.
rundeps    :
    - faba-icon-theme
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
