name       : moka-icon-theme
version    : 5.3.3
release    : 6
source     :
    - https://github.com/snwh/moka-icon-theme/archive/v5.3.3.tar.gz : 277108c39e0ebb1badd540d22511aab43d43234fbc4c24987e759c683cfdcf47
license    :
    - GPL-3.0
    - CC-BY-SA-4.0
component  : desktop.theme
summary    : Moka Icon Theme
description: |
    Moka is an icon theme designed with a minimal, flat style, using simple geometry & colours.

    Each icon has been pixel-perfectly-designed and provides several sizes for the best experience throughout your desktop.
rundeps    :
    - faba-icon-theme
install    : |
    mkdir -p $installdir/usr/share/icons/
    cp -R Moka $installdir/usr/share/icons/.
    chmod a+r -R $installdir/usr/share/icons
